name: 签到

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 15 21 * * *
  watch:
    types: started
    
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: 签到
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
        - name: Checkout codes
          uses: actions/checkout@v2
          
        - name: 运行时间
          run: |
           time=$(curl -s "http://quan.suning.com/getSysTime.do")
           echo -e "当前时间：\n${time}"
 
        - name: Run 号码1
          env:
           haoma: ${{ secrets.HAOMA }}
           mm: ${{ secrets.MM }}
           appid: ${{ secrets.APPID }}
          run: |
           bash CnUnicom.sh
           
